# Generated by Django 3.2 on 2022-03-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20220307_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=45)),
                ('emp_age', models.IntegerField()),
                ('salary', models.FloatField()),
                ('gender', models.CharField(max_length=45)),
            ],
        ),
    ]
