# Generated by Django 3.2 on 2022-03-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_uploadfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('des', models.TextField()),
                ('image', models.ImageField(upload_to='uploads/images')),
            ],
        ),
    ]
